---
name: Unit test workflow
on:
  - push
  - pull_request
jobs:
  build:
    name: Build and test default scheme
    runs-on: macos-latest
    steps:
      - name: Repository checkout
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
